# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Video_player_design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1020, 885)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 630, 631, 71))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 24, 16))
        self.label.setObjectName("label")
        self.cutStartTime = QtWidgets.QLineEdit(self.groupBox)
        self.cutStartTime.setGeometry(QtCore.QRect(50, 30, 150, 20))
        self.cutStartTime.setObjectName("cutStartTime")
        self.cutEndTime = QtWidgets.QLineEdit(self.groupBox)
        self.cutEndTime.setGeometry(QtCore.QRect(290, 30, 150, 20))
        self.cutEndTime.setObjectName("cutEndTime")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(260, 30, 18, 16))
        self.label_2.setObjectName("label_2")
        self.cutButton = QtWidgets.QPushButton(self.groupBox)
        self.cutButton.setGeometry(QtCore.QRect(500, 30, 75, 23))
        self.cutButton.setObjectName("cutButton")
        self.widget = QVideoWidget(Form)
        self.widget.setGeometry(QtCore.QRect(40, 70, 900, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.playButton = QtWidgets.QPushButton(Form)
        self.playButton.setGeometry(QtCore.QRect(0, 570, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setText("")
        self.playButton.setObjectName("playButton")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setEnabled(True)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 580, 900, 25))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.timeLcd = QtWidgets.QLCDNumber(Form)
        self.timeLcd.setGeometry(QtCore.QRect(940, 580, 80, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLcd.sizePolicy().hasHeightForWidth())
        self.timeLcd.setSizePolicy(sizePolicy)
        self.timeLcd.setObjectName("timeLcd")
        self.OpenButton = QtWidgets.QPushButton(Form)
        self.OpenButton.setGeometry(QtCore.QRect(0, 0, 81, 41))
        self.OpenButton.setObjectName("OpenButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(650, 630, 361, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.mirror_xButton = QtWidgets.QPushButton(self.groupBox_2)
        self.mirror_xButton.setGeometry(QtCore.QRect(60, 30, 75, 23))
        self.mirror_xButton.setObjectName("mirror_xButton")
        self.mirror_yButton = QtWidgets.QPushButton(self.groupBox_2)
        self.mirror_yButton.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.mirror_yButton.setObjectName("mirror_yButton")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 730, 421, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.speed_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.speed_line.setGeometry(QtCore.QRect(140, 40, 113, 20))
        self.speed_line.setObjectName("speed_line")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 111, 16))
        self.label_3.setObjectName("label_3")
        self.speedButton = QtWidgets.QPushButton(self.groupBox_3)
        self.speedButton.setGeometry(QtCore.QRect(280, 40, 101, 23))
        self.speedButton.setObjectName("speedButton")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(540, 730, 191, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.blackwhiteButton = QtWidgets.QPushButton(self.groupBox_4)
        self.blackwhiteButton.setGeometry(QtCore.QRect(40, 30, 101, 21))
        self.blackwhiteButton.setObjectName("blackwhiteButton")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(950, 0, 71, 41))
        self.saveButton.setObjectName("saveButton")
        self.redoButton = QtWidgets.QPushButton(Form)
        self.redoButton.setGeometry(QtCore.QRect(870, 0, 41, 41))
        self.redoButton.setText("")
        self.redoButton.setObjectName("redoButton")
        self.undoButton = QtWidgets.QPushButton(Form)
        self.undoButton.setGeometry(QtCore.QRect(810, 0, 41, 41))
        self.undoButton.setText("")
        self.undoButton.setObjectName("undoButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Cut"))
        self.label.setText(_translate("Form", "Start"))
        self.label_2.setText(_translate("Form", "End"))
        self.cutButton.setText(_translate("Form", "Cut"))
        self.OpenButton.setText(_translate("Form", "Open"))
        self.groupBox_2.setTitle(_translate("Form", "Mirror video"))
        self.mirror_xButton.setText(_translate("Form", "Mirror x"))
        self.mirror_yButton.setText(_translate("Form", "Mirror y"))
        self.groupBox_3.setTitle(_translate("Form", "Change speed"))
        self.label_3.setText(_translate("Form", "Coefficient of speed"))
        self.speedButton.setText(_translate("Form", "Change speed"))
        self.groupBox_4.setTitle(_translate("Form", "Blackwhite filter"))
        self.blackwhiteButton.setText(_translate("Form", "Apply filter"))
        self.saveButton.setText(_translate("Form", "Save"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
